### ISSUE TITLE
Redmine4 upgrade error

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_impersonate#1]
Test failed with the following log.

```
$ RAILS_ENV=test NAME=redmine_impersonate bundle exec rake redmine:plugins:test
Unknown database adapter `postgis` found in config/database.yml, use Gemfile.local to load your own database gems
Run options: --seed 23897

# Running:

.E

Error:
ImpersonationTest#test_impersonate_link_as_admin_in_edit:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:43:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:42

E

Error:
ImpersonationTest#test_impersonating_user_as_anonymous:
ArgumentError: unknown keyword: user_id
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:75:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:72

E

Error:
ImpersonationTest#test_stop_impersonating_user:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:82:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:81

E

Error:
ImpersonationTest#test_impersonate_link_as_user_in_user_profile:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:16:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:15

E

Error:
ImpersonationTest#test_impersonate_link_as_admin_in_admin_profile:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:34:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:33

E

Error:
ImpersonationTest#test_impersonating_user_as_user:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:63:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:62

E

Error:
ImpersonationTest#test_impersonate_link_as_admin_in_user_profile:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:25:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:24

E

Error:
ImpersonationTest#test_impersonating_user_as_admin:
ArgumentError: unknown keywords: username, password
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:96:in `log_user'
    plugins/redmine_impersonate/test/integration/impersonation_test.rb:52:in `block in <class:ImpersonationTest>'


bin/rails test plugins/redmine_impersonate/test/integration/impersonation_test.rb:51



Finished in 2.347983s, 3.8331 runs/s, 0.4259 assertions/s.
9 runs, 1 assertions, 0 failures, 8 errors, 0 skips
```

**Comment by sanak** [comment]
Close this issue, because I confirmed that this solved in the following commit:
- https://github.com/gtt-project/redmine_impersonate/commit/118c471de56fb0a8ef658e4e7de356ac1907fcfd
